[33mcommit 683e8f7059bb09f39e95e4807c2d8483408cca03[m[33m ([m[1;36mHEAD -> [m[1;32mmain[m[33m, [m[1;31morigin/main[m[33m, [m[1;31morigin/HEAD[m[33m)[m
Author: msgrigorovich <107698943+msgrigorovich@users.noreply.github.com>
Date:   Sat Jul 23 22:34:38 2022 +0300

    references for blender's models

[1mdiff --git a/BasketGolf/area/references/graffity.png b/BasketGolf/area/references/graffity.png[m
[1mnew file mode 100644[m
[1mindex 0000000..628b228[m
Binary files /dev/null and b/BasketGolf/area/references/graffity.png differ
[1mdiff --git a/BasketGolf/area/references/graffity_2.png b/BasketGolf/area/references/graffity_2.png[m
[1mnew file mode 100644[m
[1mindex 0000000..0a38df9[m
Binary files /dev/null and b/BasketGolf/area/references/graffity_2.png differ
[1mdiff --git a/BasketGolf/area/references/graffity_fone.png b/BasketGolf/area/references/graffity_fone.png[m
[1mnew file mode 100644[m
[1mindex 0000000..b1775f8[m
Binary files /dev/null and b/BasketGolf/area/references/graffity_fone.png differ
[1mdiff --git a/BasketGolf/area/references/lamp.jpg b/BasketGolf/area/references/lamp.jpg[m
[1mnew file mode 100644[m
[1mindex 0000000..aabcc13[m
Binary files /dev/null and b/BasketGolf/area/references/lamp.jpg differ
[1mdiff --git a/BasketGolf/area/references/metall texture.jpg b/BasketGolf/area/references/metall texture.jpg[m
[1mnew file mode 100644[m
[1mindex 0000000..a25703a[m
Binary files /dev/null and b/BasketGolf/area/references/metall texture.jpg differ
[1mdiff --git a/BasketGolf/area/references/ring.jpg b/BasketGolf/area/references/ring.jpg[m
[1mnew file mode 100644[m
[1mindex 0000000..312806c[m
Binary files /dev/null and b/BasketGolf/area/references/ring.jpg differ
[1mdiff --git a/BasketGolf/area/references/smile.webp b/BasketGolf/area/references/smile.webp[m
[1mnew file mode 100644[m
[1mindex 0000000..3c7fb4a[m
Binary files /dev/null and b/BasketGolf/area/references/smile.webp differ
[1mdiff --git a/BasketGolf/area/references/spider fone.jpg b/BasketGolf/area/references/spider fone.jpg[m
[1mnew file mode 100644[m
[1mindex 0000000..e6eeb18[m
Binary files /dev/null and b/BasketGolf/area/references/spider fone.jpg differ
[1mdiff --git a/BasketGolf/area/references/spider.jpg b/BasketGolf/area/references/spider.jpg[m
[1mnew file mode 100644[m
[1mindex 0000000..2b4a5fb[m
Binary files /dev/null and b/BasketGolf/area/references/spider.jpg differ
[1mdiff --git a/BasketGolf/area/references/spider_black.jpg b/BasketGolf/area/references/spider_black.jpg[m
[1mnew file mode 100644[m
[1mindex 0000000..b143fea[m
Binary files /dev/null and b/BasketGolf/area/references/spider_black.jpg differ
[1mdiff --git a/BasketGolf/area/references/trash logo.jpg b/BasketGolf/area/references/trash logo.jpg[m
[1mnew file mode 100644[m
[1mindex 0000000..4099bd0[m
Binary files /dev/null and b/BasketGolf/area/references/trash logo.jpg differ
[1mdiff --git a/BasketGolf/area/references/trash logo_2.png b/BasketGolf/area/references/trash logo_2.png[m
[1mnew file mode 100644[m
[1mindex 0000000..5ecc50c[m
Binary files /dev/null and b/BasketGolf/area/references/trash logo_2.png differ
[1mdiff --git a/BasketGolf/area/references/trash texture.jpg b/BasketGolf/area/references/trash texture.jpg[m
[1mnew file mode 100644[m
[1mindex 0000000..94a936e[m
Binary files /dev/null and b/BasketGolf/area/references/trash texture.jpg differ
[1mdiff --git a/BasketGolf/area/references/trash.jpg b/BasketGolf/area/references/trash.jpg[m
[1mnew file mode 100644[m
[1mindex 0000000..e7329eb[m
Binary files /dev/null and b/BasketGolf/area/references/trash.jpg differ
[1mdiff --git a/BasketGolf/area/references/witcher.png b/BasketGolf/area/references/witcher.png[m
[1mnew file mode 100644[m
[1mindex 0000000..21bcd6a[m
Binary files /dev/null and b/BasketGolf/area/references/witcher.png differ
